# Долги гостей + şubeler arası alışveriş (owner 2026-10-06).
# Çalıştırma: rm -f /tmp/gb.db; PYTHONPATH=. DB_PATH=/tmp/gb.db BOT_TOKEN=123:abc python tests/gdebt_brx_test.py
import asyncio, json, bot
FAIL = []
def check(c, m):
    print(('  ok  ' if c else '  FAIL ') + m)
    if not c: FAIL.append(m)
db = bot.get_db()
sent = []
class FB:
    async def send_message(self, chat_id=None, text=None, *a, **k): sent.append((chat_id, text))
    def __getattr__(self, n):
        async def f(*a, **k): return None
        return f
def act(uid, p):
    sent.clear()
    asyncio.run(bot.handle_webapp_data(bot._ShimUpdate(FB(), uid, f'U{uid}', None, json.dumps(p)), bot._ShimContext(FB(), {}, uid=uid)))
db.execute("UPDATE branches SET name='C5', group_chat_id='-1001' WHERE id=1")
db.execute("INSERT OR REPLACE INTO branches (id,name,group_chat_id,sort_order,active) VALUES (2,'Magic','-1002',2,1)")
db.execute("INSERT OR REPLACE INTO users (user_id,name,role,approved,authorized) VALUES (1,'Owner','owner',1,1)")
db.execute("INSERT OR REPLACE INTO users (user_id,name,role,branch_id,approved,authorized) VALUES (10,'Бек','barista',1,1,1)")
db.commit()
print('Долги гостей')
act(10, {'action': 'gdebt_guest_add', 'name': ' Алишер  ака ', 'branch_id': 1, 'amount': 45})
v = bot.gdebt_view(db); g = v['guests'][0]
check(g['n'] == 'Алишер ака' and g['bal'] == 45000 and g['bid'] == 1, 'yeni misafir + ilk borç (45 → 45 000)')
act(10, {'action': 'gdebt_guest_add', 'name': 'алишер АКА', 'branch_id': 1})
check(len(bot.gdebt_view(db)['guests']) == 1, 'aynı ad aynı şubede tekrar açılmaz')
act(10, {'action': 'gdebt_tx', 'guest_id': g['id'], 'kind': 'pay', 'amount': 20000})
act(10, {'action': 'gdebt_tx', 'guest_id': g['id'], 'kind': 'debt', 'amount': 12000})
check(bot.gdebt_view(db)['guests'][0]['bal'] == 37000, 'ödeme düşer, yeni borç eklenir (37 000)')
tx = bot.gdebt_view(db)['tx'][0]
act(10, {'action': 'gdebt_void', 'id': tx['id']})
check(bot.gdebt_view(db)['guests'][0]['bal'] == 37000, 'çalışan kayıt silemez')
act(1, {'action': 'gdebt_void', 'id': tx['id']})
check(bot.gdebt_view(db)['guests'][0]['bal'] == 25000, 'owner siler → bakiye 25 000')
print('Şubeler arası')
act(1, {'action': 'brx_add', 'from': 2, 'to': 1, 'item': 'Стакан 300', 'unit': 'шт', 'qty': 400})   # owner taşıdı
check(any(c == -1001 for c, _ in sent) and any(c == -1002 for c, _ in sent), 'iki şube grubuna bildirim')
act(10, {'action': 'brx_add', 'from': 1, 'to': 2, 'item': 'стакан 300', 'unit': 'шт', 'qty': 200})
act(10, {'action': 'brx_add', 'from': 1, 'to': 2, 'item': 'Кофе эспрессо', 'unit': 'кг', 'qty': '1,5'})
b = bot.brx_balance(db)[(1, 2)]
check(b[('стакан 300', 'шт')] == -200, 'Magic 400 verdi, C5 200 geri → C5 Magic\'e 200 borçlu')
check(b[('кофе эспрессо', 'кг')] == 1.5, 'kahve 1,5 kg: Magic C5\'e borçlu')
act(10, {'action': 'brx_add', 'from': 1, 'to': 1, 'item': 'X', 'qty': 1})
check(len(bot.brx_view(db)) == 3, 'aynı şube reddedilir')
act(1, {'action': 'brx_void', 'id': bot.brx_view(db)[0]['id']})
check(len(bot.brx_view(db)) == 2, 'owner kaydı siler')
print('Kapanış raporu')
act(10, {'action': 'cash_report', 'branch_id': 1, 'cups': [], 'expenses': [{'n': 'В долг · Новый гость', 'a': 30000}],
         'gdebts': [{'g': 0, 'n': 'Новый гость', 'a': 30000, 'k': 'debt'}, {'g': g['id'], 'n': g['n'], 'a': 5000, 'k': 'pay'}], 'note': ''})
v = bot.gdebt_view(db); gm = {x['n']: x['bal'] for x in v['guests']}
check(gm.get('Новый гость') == 30000, 'rapordaki yeni misafir + borç yazıldı')
check(gm.get('Алишер ака') == 20000, 'rapordaki ödeme düştü (25 000 → 20 000)')
check(any('Долги гостей' in (t or '') for c, t in sent if c == -1001), 'grup raporunda «Долги гостей» bölümü')
print('Şube kısıtı')
gm2 = bot.gdebt_guest_get_or_create(db, 0, 'Гость Magic', 2, 1, 'Owner'); bot.gdebt_add_tx(db, gm2, 'debt', 10000, 2, 1, 'Owner'); db.commit()
check(all(g['bid'] == 1 for g in bot.gdebt_view(db, 1)['guests']) and any(g['bid'] == 2 for g in bot.gdebt_view(db)['guests']), 'çalışan görünümü yalnız kendi şubesi, owner hepsi')
act(10, {'action': 'gdebt_tx', 'guest_id': gm2, 'kind': 'pay', 'amount': 10000})
check({g['id']: g['bal'] for g in bot.gdebt_view(db)['guests']}[gm2] == 10000, 'çalışan başka şubenin misafirine yazamaz')
db.execute("INSERT OR REPLACE INTO branches (id,name,group_chat_id,sort_order,active) VALUES (3,'NewWay','-1003',3,1)"); db.commit()
n0 = len(bot.brx_view(db))
act(10, {'action': 'brx_add', 'from': 2, 'to': 3, 'item': 'Молоко', 'unit': 'л', 'qty': 5})
check(len(bot.brx_view(db)) == n0, 'çalışan kendi şubesi dışındaki transferi yazamaz')
act(10, {'action': 'brx_add', 'from': 2, 'to': 1, 'item': 'Молоко', 'unit': 'л', 'qty': 5})
check(len(bot.brx_view(db)) == n0, 'çalışan «aldım» yazamaz — yalnız şu anki şubesinden gönderir')
db.execute("INSERT OR REPLACE INTO meta (k,val) VALUES ('cur_branch_10','2')"); db.commit()
act(10, {'action': 'brx_add', 'from': 2, 'to': 3, 'item': 'Молоко', 'unit': 'л', 'qty': 5})
check(len(bot.brx_view(db)) == n0 + 1, 'şube değiştirince (Magic) yeni şubeden gönderebilir')
act(10, {'action': 'brx_add', 'from': 1, 'to': 3, 'item': 'Молоко', 'unit': 'л', 'qty': 5})
check(len(bot.brx_view(db)) == n0 + 1, 'şube değiştirince eski şubeden gönderemez')
db.execute("DELETE FROM meta WHERE k='cur_branch_10'"); db.commit()
check(all(1 in (x['f'], x['t']) for x in bot.brx_view(db, 1)), 'transfer görünümü yalnız kendi şubesi')
pay2 = bot.build_hash_payload(db, 10, 'Бек')
check('Гость Magic' not in __import__('urllib.parse', fromlist=['unquote']).unquote(pay2), 'çalışan payload\'ında başka şubenin misafiri yok')
print('PIN + şu anki şube')
import urllib.parse as _up
def gpay(uid):
    pl = bot.build_hash_payload(db, uid, 'x'); i = pl.index('gdebt=') + 6; j = pl.find('&', i)
    return json.loads(_up.unquote(pl[i:j if j > 0 else None]))
check(gpay(10)['locked'] == 0, 'PIN yokken açık')
act(10, {'action': 'gdebt_pin_set', 'pin': '1234'})
check(not bot.gdebt_pin_set(db), 'çalışan PIN koyamaz')
act(1, {'action': 'gdebt_pin_set', 'pin': '4321'})
g10 = gpay(10)
check(g10['locked'] == 1 and g10['guests'] == [] and g10['tx'] == [], 'PIN konunca çalışana liste HİÇ gelmez')
check(gpay(1)['locked'] == 0 and len(gpay(1)['guests']) > 0, 'owner her zaman görür')
n0 = len(bot.gdebt_view(db)['guests'])
act(10, {'action': 'gdebt_guest_add', 'name': 'Кто-то', 'branch_id': 1})
check(len(bot.gdebt_view(db)['guests']) == n0, 'kilitliyken çalışan kayıt yazamaz')
act(10, {'action': 'gdebt_unlock', 'pin': '0000'})
check(gpay(10)['locked'] == 1 and any('Неверный PIN' in (t or '') for c, t in sent), 'yanlış PIN açmaz')
act(10, {'action': 'gdebt_unlock', 'pin': '4321'})
check(gpay(10)['locked'] == 0 and all(g['bid'] == 1 for g in gpay(10)['guests']), 'doğru PIN → açılır (kendi şubesi)')
db.execute("INSERT OR REPLACE INTO meta (k,val) VALUES ('cur_branch_10','2')"); db.commit()
check(gpay(10)['guests'] and all(g['bid'] == 2 for g in gpay(10)['guests']), 'şube değiştirince (Magic) o şubenin misafirleri')
db.execute("DELETE FROM meta WHERE k='cur_branch_10'"); db.commit()
act(10, {'action': 'gdebt_lock'})
check(gpay(10)['locked'] == 1, 'ekrandan çıkınca (gdebt_lock) hemen kilitlenir')
act(10, {'action': 'gdebt_unlock', 'pin': '4321'})
_u = db.execute("SELECT val FROM meta WHERE k='gdebt_unl_10'").fetchone()[0]
from datetime import datetime as _dt
check((_dt.fromisoformat(_u) - _dt.now(bot.TZ)).total_seconds() <= 15 * 60 + 5, 'açık kalma en fazla 15 dk')
act(1, {'action': 'gdebt_pin_set', 'pin': '9999'})
check(gpay(10)['locked'] == 1, 'yeni PIN → herkes yeniden girer')
for _ in range(5): act(10, {'action': 'gdebt_unlock', 'pin': '1111'})
act(10, {'action': 'gdebt_unlock', 'pin': '9999'})
check(gpay(10)['locked'] == 1 and any('попыток' in (t or '') for c, t in sent), '5 yanlıştan sonra 10 dk bekleme')
g10l = gpay(10)
check(g10l['locked'] == 1 and g10l['names'] and all(set(x) == {'id', 'n', 'bid'} for x in g10l['names']) and all(x['bid'] == 1 for x in g10l['names']),
      'kilitliyken kapanış araması için YALNIZ adlar (tutar yok, kendi şubesi)')
act(1, {'action': 'gdebt_pin_set', 'pin': ''})
check(gpay(10)['locked'] == 0, 'PIN kaldırılınca açık')
print('Депозит')
gd = bot.gdebt_guest_get_or_create(db, 0, 'Вафохон', 1, 1, 'Owner'); db.commit()
act(10, {'action': 'gdebt_tx', 'guest_id': gd, 'kind': 'dep', 'amount': 300000})
bal = lambda: {g['id']: g['bal'] for g in bot.gdebt_view(db)['guests']}[gd]
check(bal() == -300000, 'depozit → eksi bakiye (300 000 depozit)')
act(10, {'action': 'gdebt_tx', 'guest_id': gd, 'kind': 'debt', 'amount': 36000})
check(bal() == -264000, 'içtikçe depozitten düşer (264 000 kaldı)')
act(10, {'action': 'cash_report', 'branch_id': 1, 'cups': [], 'expenses': [], 'note': '', 'gdebts': [{'g': gd, 'n': 'Вафохон', 'a': 50000, 'k': 'dep'}]})
check(bal() == -314000 and any('Депозит: Вафохон' in (t or '') for c, t in sent), 'kapanıştan depozit + raporda «Депозит» satırı')
print('Kalem (düzelt)')
txid = [x for x in bot.gdebt_view(db)['tx'] if x['g'] == gd and x['k'] == 'debt'][0]['id']
act(10, {'action': 'gdebt_tx_edit', 'id': txid, 'kind': 'debt', 'amount': 46000})
check(bal() == -314000, 'çalışan kaydı düzeltemez')
act(1, {'action': 'gdebt_tx_edit', 'id': txid, 'kind': 'debt', 'amount': 46000, 'note': '3 латте'})
check(bal() == -304000, 'owner tutarı düzeltir (36 000 → 46 000)')
act(1, {'action': 'gdebt_tx_edit', 'id': txid, 'kind': 'dep', 'amount': 46000})
check(bal() == -396000, 'owner türü düzeltir (Взял → Депозит)')
act(1, {'action': 'gdebt_guest_edit', 'guest_id': gd, 'name': ' Вафохон  ака ', 'phone': '+998 90'})
_g = [g for g in bot.gdebt_view(db)['guests'] if g['id'] == gd][0]
check(_g['n'] == 'Вафохон ака' and _g['ph'] == '+998 90', 'owner adı/telefonu düzeltir')
act(10, {'action': 'gdebt_guest_edit', 'guest_id': gd, 'name': 'X'})
check([g for g in bot.gdebt_view(db)['guests'] if g['id'] == gd][0]['n'] == 'Вафохон ака', 'çalışan adı değiştiremez')
print('Payload')
pay = bot.build_hash_payload(db, 10, 'Бек')
check('gdebt=' in pay and 'brx=' in pay, 'çalışan payload\'ı ikisini de taşıyor')
print('FAIL' if FAIL else 'ALL OK', FAIL)
